import type { LucideIcon } from 'lucide-react';
import { Flag, Hand, Hash, Heart, Lightbulb, PawPrint, Pizza, Plane, Smile, Trophy } from 'lucide-react';

export enum ReactionCategory {
    SMILEYS = 'smileys',
    HEARTS = 'hearts',
    GESTURES = 'gestures',
    ANIMALS = 'animals',
    FOOD = 'food',
    ACTIVITIES = 'activities',
    TRAVEL = 'travel',
    OBJECTS = 'objects',
    SYMBOLS = 'symbols',
    FLAGS = 'flags',
}

export type ReactionOption = {
    code: string;
    emoji: string;
    label: string;
    category: ReactionCategory;
}

export type ReactionCategoryMeta = {
    id: ReactionCategory;
    title: string;
    Icon: LucideIcon;
}

export const REACTION_CATEGORIES: ReactionCategoryMeta[] = [
    { id: ReactionCategory.SMILEYS, title: 'Smileys & People', Icon: Smile },
    { id: ReactionCategory.HEARTS, title: 'Hearts & Love', Icon: Heart },
    { id: ReactionCategory.GESTURES, title: 'Gestures & Hands', Icon: Hand },
    { id: ReactionCategory.ANIMALS, title: 'Animals & Nature', Icon: PawPrint },
    { id: ReactionCategory.FOOD, title: 'Food & Drink', Icon: Pizza },
    { id: ReactionCategory.ACTIVITIES, title: 'Activities & Sports', Icon: Trophy },
    { id: ReactionCategory.TRAVEL, title: 'Travel & Places', Icon: Plane },
    { id: ReactionCategory.OBJECTS, title: 'Objects', Icon: Lightbulb },
    { id: ReactionCategory.SYMBOLS, title: 'Symbols', Icon: Hash },
    { id: ReactionCategory.FLAGS, title: 'Flags', Icon: Flag },
];

export const REACTION_DETAILS: Record<string, Omit<ReactionOption, 'code'>> = {
    smile: { emoji: '🙂', label: 'Smile', category: ReactionCategory.SMILEYS },
    grinning: { emoji: '😀', label: 'Grinning', category: ReactionCategory.SMILEYS },
    joy: { emoji: '😂', label: 'Tears of joy', category: ReactionCategory.SMILEYS },
    rofl: { emoji: '🤣', label: 'ROFL', category: ReactionCategory.SMILEYS },
    sweat_smile: { emoji: '😅', label: 'Sweat smile', category: ReactionCategory.SMILEYS },
    beaming: { emoji: '😁', label: 'Beaming', category: ReactionCategory.SMILEYS },
    wink: { emoji: '😉', label: 'Wink', category: ReactionCategory.SMILEYS },
    blush: { emoji: '😊', label: 'Blush', category: ReactionCategory.SMILEYS },
    innocent: { emoji: '😇', label: 'Innocent', category: ReactionCategory.SMILEYS },
    smiling_hearts: { emoji: '🥰', label: 'Smiling with hearts', category: ReactionCategory.SMILEYS },
    heart_eyes: { emoji: '😍', label: 'Heart eyes', category: ReactionCategory.SMILEYS },
    kiss: { emoji: '😘', label: 'Blowing a kiss', category: ReactionCategory.SMILEYS },
    star_struck: { emoji: '🤩', label: 'Star struck', category: ReactionCategory.SMILEYS },
    yum: { emoji: '😋', label: 'Yum', category: ReactionCategory.SMILEYS },
    tongue: { emoji: '😛', label: 'Tongue', category: ReactionCategory.SMILEYS },
    winking_tongue: { emoji: '😜', label: 'Winking with tongue', category: ReactionCategory.SMILEYS },
    zany: { emoji: '🤪', label: 'Zany', category: ReactionCategory.SMILEYS },
    glasses: { emoji: '😎', label: 'Glasses', category: ReactionCategory.SMILEYS },
    partying: { emoji: '🥳', label: 'Partying', category: ReactionCategory.SMILEYS },
    relieved: { emoji: '😌', label: 'Relieved', category: ReactionCategory.SMILEYS },
    upside_down: { emoji: '🙃', label: 'Upside down', category: ReactionCategory.SMILEYS },
    smirking: { emoji: '😏', label: 'Smirking', category: ReactionCategory.SMILEYS },
    thinking: { emoji: '🤔', label: 'Thinking', category: ReactionCategory.SMILEYS },
    hug: { emoji: '🤗', label: 'Hug', category: ReactionCategory.SMILEYS },
    hand_over_mouth: { emoji: '🤭', label: 'Hand over mouth', category: ReactionCategory.SMILEYS },
    peeking: { emoji: '🫢', label: 'Peeking', category: ReactionCategory.SMILEYS },
    saluting: { emoji: '🫡', label: 'Saluting', category: ReactionCategory.SMILEYS },
    rolling_eyes: { emoji: '🙄', label: 'Rolling eyes', category: ReactionCategory.SMILEYS },
    grimacing: { emoji: '😬', label: 'Grimacing', category: ReactionCategory.SMILEYS },
    flushed: { emoji: '😳', label: 'Flushed', category: ReactionCategory.SMILEYS },
    pleading: { emoji: '🥺', label: 'Pleading', category: ReactionCategory.SMILEYS },
    holding_back_tears: { emoji: '🥹', label: 'Holding back tears', category: ReactionCategory.SMILEYS },
    crying: { emoji: '😢', label: 'Crying', category: ReactionCategory.SMILEYS },
    loudly_crying: { emoji: '😭', label: 'Loudly crying', category: ReactionCategory.SMILEYS },
    triumph: { emoji: '😤', label: 'Triumph', category: ReactionCategory.SMILEYS },
    angry: { emoji: '😡', label: 'Angry', category: ReactionCategory.SMILEYS },
    cursing: { emoji: '🤬', label: 'Cursing', category: ReactionCategory.SMILEYS },
    exploding_head: { emoji: '🤯', label: 'Exploding head', category: ReactionCategory.SMILEYS },
    screaming: { emoji: '😱', label: 'Screaming', category: ReactionCategory.SMILEYS },
    cold_face: { emoji: '🥶', label: 'Cold face', category: ReactionCategory.SMILEYS },
    hot_face: { emoji: '🥵', label: 'Hot face', category: ReactionCategory.SMILEYS },
    sleeping: { emoji: '😴', label: 'Sleeping', category: ReactionCategory.SMILEYS },
    drooling: { emoji: '🤤', label: 'Drooling', category: ReactionCategory.SMILEYS },
    mask: { emoji: '😷', label: 'Medical mask', category: ReactionCategory.SMILEYS },
    woozy: { emoji: '🥴', label: 'Woozy', category: ReactionCategory.SMILEYS },
    cowboy: { emoji: '🤠', label: 'Cowboy', category: ReactionCategory.SMILEYS },
    clown: { emoji: '🤡', label: 'Clown', category: ReactionCategory.SMILEYS },
    skull: { emoji: '💀', label: 'Skull', category: ReactionCategory.SMILEYS },
    ghost: { emoji: '👻', label: 'Ghost', category: ReactionCategory.SMILEYS },
    poop: { emoji: '💩', label: 'Pile of poo', category: ReactionCategory.SMILEYS },
    smiling_imp: { emoji: '😈', label: 'Smiling imp', category: ReactionCategory.SMILEYS },

    heart: { emoji: '❤️', label: 'Heart', category: ReactionCategory.HEARTS },
    orange_heart: { emoji: '🧡', label: 'Orange heart', category: ReactionCategory.HEARTS },
    yellow_heart: { emoji: '💛', label: 'Yellow heart', category: ReactionCategory.HEARTS },
    green_heart: { emoji: '💚', label: 'Green heart', category: ReactionCategory.HEARTS },
    blue_heart: { emoji: '💙', label: 'Blue heart', category: ReactionCategory.HEARTS },
    purple_heart: { emoji: '💜', label: 'Purple heart', category: ReactionCategory.HEARTS },
    black_heart: { emoji: '🖤', label: 'Black heart', category: ReactionCategory.HEARTS },
    white_heart: { emoji: '🤍', label: 'White heart', category: ReactionCategory.HEARTS },
    two_hearts: { emoji: '💕', label: 'Two hearts', category: ReactionCategory.HEARTS },
    revolving_hearts: { emoji: '💞', label: 'Revolving hearts', category: ReactionCategory.HEARTS },
    heartbeat: { emoji: '💓', label: 'Beating heart', category: ReactionCategory.HEARTS },
    growing_heart: { emoji: '💗', label: 'Growing heart', category: ReactionCategory.HEARTS },
    sparkling_heart: { emoji: '💖', label: 'Sparkling heart', category: ReactionCategory.HEARTS },
    heart_arrow: { emoji: '💘', label: 'Heart with arrow', category: ReactionCategory.HEARTS },
    heart_on_fire: { emoji: '❤️‍🔥', label: 'Heart on fire', category: ReactionCategory.HEARTS },
    broken_heart: { emoji: '💔', label: 'Broken heart', category: ReactionCategory.HEARTS },
    kiss_mark: { emoji: '💋', label: 'Kiss mark', category: ReactionCategory.HEARTS },

    thumbs_up: { emoji: '👍', label: 'Thumbs up', category: ReactionCategory.GESTURES },
    thumbs_down: { emoji: '👎', label: 'Thumbs down', category: ReactionCategory.GESTURES },
    clap: { emoji: '👏', label: 'Clapping hands', category: ReactionCategory.GESTURES },
    raised_hands: { emoji: '🙌', label: 'Raised hands', category: ReactionCategory.GESTURES },
    pray: { emoji: '🙏', label: 'Pray', category: ReactionCategory.GESTURES },
    handshake: { emoji: '🤝', label: 'Handshake', category: ReactionCategory.GESTURES },
    crossed_fingers: { emoji: '🤞', label: 'Crossed fingers', category: ReactionCategory.GESTURES },
    love_you: { emoji: '🤟', label: 'Love you gesture', category: ReactionCategory.GESTURES },
    rock_on: { emoji: '🤘', label: 'Rock on', category: ReactionCategory.GESTURES },
    call_me: { emoji: '🤙', label: 'Call me hand', category: ReactionCategory.GESTURES },
    ok_hand: { emoji: '👌', label: 'OK hand', category: ReactionCategory.GESTURES },
    pinched_fingers: { emoji: '🤌', label: 'Pinched fingers', category: ReactionCategory.GESTURES },
    victory: { emoji: '✌️', label: 'Victory hand', category: ReactionCategory.GESTURES },
    heart_hands: { emoji: '🫶', label: 'Heart hands', category: ReactionCategory.GESTURES },
    flexed_biceps: { emoji: '💪', label: 'Flexed biceps', category: ReactionCategory.GESTURES },
    raised_fist: { emoji: '✊', label: 'Raised fist', category: ReactionCategory.GESTURES },
    fist_bump: { emoji: '👊', label: 'Fist bump', category: ReactionCategory.GESTURES },
    wave: { emoji: '👋', label: 'Waving hand', category: ReactionCategory.GESTURES },
    raised_hand: { emoji: '🖐️', label: 'Raised hand', category: ReactionCategory.GESTURES },
    finger_up: { emoji: '☝️', label: 'Finger up', category: ReactionCategory.GESTURES },
    finger_down: { emoji: '👇', label: 'Finger down', category: ReactionCategory.GESTURES },
    middle_finger: { emoji: '🖕', label: 'Middle finger', category: ReactionCategory.GESTURES },
    man_shrugging: { emoji: '🤷‍♂️', label: 'Man shrugging', category: ReactionCategory.GESTURES },
    woman_shrugging: { emoji: '🤷‍♀️', label: 'Woman shrugging', category: ReactionCategory.GESTURES },
    person_shrugging: { emoji: '🤷', label: 'Person shrugging', category: ReactionCategory.GESTURES },
    eyes: { emoji: '👀', label: 'Eyes', category: ReactionCategory.GESTURES },

    dog: { emoji: '🐶', label: 'Dog', category: ReactionCategory.ANIMALS },
    cat: { emoji: '🐱', label: 'Cat', category: ReactionCategory.ANIMALS },
    fox: { emoji: '🦊', label: 'Fox', category: ReactionCategory.ANIMALS },
    bear: { emoji: '🐻', label: 'Bear', category: ReactionCategory.ANIMALS },
    panda: { emoji: '🐼', label: 'Panda', category: ReactionCategory.ANIMALS },
    lion: { emoji: '🦁', label: 'Lion', category: ReactionCategory.ANIMALS },
    frog: { emoji: '🐸', label: 'Frog', category: ReactionCategory.ANIMALS },
    monkey: { emoji: '🐵', label: 'Monkey', category: ReactionCategory.ANIMALS },
    see_no_evil: { emoji: '🙈', label: 'See no evil', category: ReactionCategory.ANIMALS },
    unicorn: { emoji: '🦄', label: 'Unicorn', category: ReactionCategory.ANIMALS },
    butterfly: { emoji: '🦋', label: 'Butterfly', category: ReactionCategory.ANIMALS },
    blossom: { emoji: '🌸', label: 'Cherry blossom', category: ReactionCategory.ANIMALS },
    rose: { emoji: '🌹', label: 'Rose', category: ReactionCategory.ANIMALS },
    sunflower: { emoji: '🌻', label: 'Sunflower', category: ReactionCategory.ANIMALS },
    four_leaf_clover: { emoji: '🍀', label: 'Four leaf clover', category: ReactionCategory.ANIMALS },
    rainbow: { emoji: '🌈', label: 'Rainbow', category: ReactionCategory.ANIMALS },
    sun: { emoji: '☀️', label: 'Sun', category: ReactionCategory.ANIMALS },
    star: { emoji: '⭐', label: 'Star', category: ReactionCategory.ANIMALS },

    pizza: { emoji: '🍕', label: 'Pizza', category: ReactionCategory.FOOD },
    burger: { emoji: '🍔', label: 'Burger', category: ReactionCategory.FOOD },
    fries: { emoji: '🍟', label: 'French fries', category: ReactionCategory.FOOD },
    taco: { emoji: '🌮', label: 'Taco', category: ReactionCategory.FOOD },
    popcorn: { emoji: '🍿', label: 'Popcorn', category: ReactionCategory.FOOD },
    donut: { emoji: '🍩', label: 'Donut', category: ReactionCategory.FOOD },
    birthday_cake: { emoji: '🎂', label: 'Birthday cake', category: ReactionCategory.FOOD },
    cake: { emoji: '🍰', label: 'Cake', category: ReactionCategory.FOOD },
    chocolate: { emoji: '🍫', label: 'Chocolate', category: ReactionCategory.FOOD },
    apple: { emoji: '🍎', label: 'Apple', category: ReactionCategory.FOOD },
    strawberry: { emoji: '🍓', label: 'Strawberry', category: ReactionCategory.FOOD },
    avocado: { emoji: '🥑', label: 'Avocado', category: ReactionCategory.FOOD },
    coffee: { emoji: '☕', label: 'Coffee', category: ReactionCategory.FOOD },
    beer: { emoji: '🍺', label: 'Beer', category: ReactionCategory.FOOD },
    beers: { emoji: '🍻', label: 'Clinking beers', category: ReactionCategory.FOOD },
    clinking_glasses: { emoji: '🥂', label: 'Clinking glasses', category: ReactionCategory.FOOD },
    wine: { emoji: '🍷', label: 'Wine', category: ReactionCategory.FOOD },
    champagne: { emoji: '🍾', label: 'Champagne', category: ReactionCategory.FOOD },

    runner: { emoji: '🏃', label: 'Runner', category: ReactionCategory.ACTIVITIES },
    snowboarder: { emoji: '🏂', label: 'Snowboarder', category: ReactionCategory.ACTIVITIES },
    cyclist: { emoji: '🚴', label: 'Cyclist', category: ReactionCategory.ACTIVITIES },
    weightlifter: { emoji: '🏋️', label: 'Weightlifter', category: ReactionCategory.ACTIVITIES },
    cartwheel: { emoji: '🤸', label: 'Cartwheel', category: ReactionCategory.ACTIVITIES },
    lotus: { emoji: '🧘', label: 'Meditation', category: ReactionCategory.ACTIVITIES },
    surfer: { emoji: '🏄', label: 'Surfer', category: ReactionCategory.ACTIVITIES },
    soccer: { emoji: '⚽', label: 'Soccer ball', category: ReactionCategory.ACTIVITIES },
    basketball: { emoji: '🏀', label: 'Basketball', category: ReactionCategory.ACTIVITIES },
    tennis: { emoji: '🎾', label: 'Tennis', category: ReactionCategory.ACTIVITIES },
    ping_pong: { emoji: '🏓', label: 'Ping pong', category: ReactionCategory.ACTIVITIES },
    boxing_glove: { emoji: '🥊', label: 'Boxing glove', category: ReactionCategory.ACTIVITIES },
    dart: { emoji: '🎯', label: 'Bullseye', category: ReactionCategory.ACTIVITIES },
    bowling: { emoji: '🎳', label: 'Bowling', category: ReactionCategory.ACTIVITIES },
    video_game: { emoji: '🎮', label: 'Video game', category: ReactionCategory.ACTIVITIES },
    dice: { emoji: '🎲', label: 'Dice', category: ReactionCategory.ACTIVITIES },
    guitar: { emoji: '🎸', label: 'Guitar', category: ReactionCategory.ACTIVITIES },
    microphone: { emoji: '🎤', label: 'Microphone', category: ReactionCategory.ACTIVITIES },
    headphones: { emoji: '🎧', label: 'Headphones', category: ReactionCategory.ACTIVITIES },
    clapper: { emoji: '🎬', label: 'Clapper board', category: ReactionCategory.ACTIVITIES },
    art: { emoji: '🎨', label: 'Artist palette', category: ReactionCategory.ACTIVITIES },
    trophy: { emoji: '🏆', label: 'Trophy', category: ReactionCategory.ACTIVITIES },

    rocket: { emoji: '🚀', label: 'Rocket', category: ReactionCategory.TRAVEL },
    airplane: { emoji: '✈️', label: 'Airplane', category: ReactionCategory.TRAVEL },
    car: { emoji: '🚗', label: 'Car', category: ReactionCategory.TRAVEL },
    racing_car: { emoji: '🏎️', label: 'Racing car', category: ReactionCategory.TRAVEL },
    train: { emoji: '🚂', label: 'Locomotive', category: ReactionCategory.TRAVEL },
    sailboat: { emoji: '⛵', label: 'Sailboat', category: ReactionCategory.TRAVEL },
    beach: { emoji: '🏖️', label: 'Beach', category: ReactionCategory.TRAVEL },
    desert_island: { emoji: '🏝️', label: 'Desert island', category: ReactionCategory.TRAVEL },
    world_map: { emoji: '🗺️', label: 'World map', category: ReactionCategory.TRAVEL },
    tower: { emoji: '🗼', label: 'Tower', category: ReactionCategory.TRAVEL },
    castle: { emoji: '🏰', label: 'Castle', category: ReactionCategory.TRAVEL },
    house: { emoji: '🏠', label: 'House', category: ReactionCategory.TRAVEL },
    globe: { emoji: '🌍', label: 'Globe', category: ReactionCategory.TRAVEL },

    hour_glass: { emoji: '⌛', label: 'Hour glass', category: ReactionCategory.OBJECTS },
    bulb: { emoji: '💡', label: 'Light bulb', category: ReactionCategory.OBJECTS },
    mobile_phone: { emoji: '📱', label: 'Mobile phone', category: ReactionCategory.OBJECTS },
    laptop: { emoji: '💻', label: 'Laptop', category: ReactionCategory.OBJECTS },
    watch: { emoji: '⌚', label: 'Watch', category: ReactionCategory.OBJECTS },
    camera: { emoji: '📷', label: 'Camera', category: ReactionCategory.OBJECTS },
    gift: { emoji: '🎁', label: 'Gift', category: ReactionCategory.OBJECTS },
    balloon: { emoji: '🎈', label: 'Balloon', category: ReactionCategory.OBJECTS },
    money_bag: { emoji: '💰', label: 'Money bag', category: ReactionCategory.OBJECTS },
    gem: { emoji: '💎', label: 'Gem stone', category: ReactionCategory.OBJECTS },
    key: { emoji: '🔑', label: 'Key', category: ReactionCategory.OBJECTS },
    books: { emoji: '📚', label: 'Books', category: ReactionCategory.OBJECTS },
    pencil: { emoji: '✏️', label: 'Pencil', category: ReactionCategory.OBJECTS },

    fire: { emoji: '🔥', label: 'Fire', category: ReactionCategory.SYMBOLS },
    hundred: { emoji: '💯', label: 'Hundred', category: ReactionCategory.SYMBOLS },
    sparkles: { emoji: '✨', label: 'Sparkles', category: ReactionCategory.SYMBOLS },
    check: { emoji: '✅', label: 'Check mark', category: ReactionCategory.SYMBOLS },
    cross: { emoji: '❌', label: 'Cross mark', category: ReactionCategory.SYMBOLS },
    exclamation: { emoji: '❗', label: 'Exclamation mark', category: ReactionCategory.SYMBOLS },
    question: { emoji: '❓', label: 'Question mark', category: ReactionCategory.SYMBOLS },
    warning: { emoji: '⚠️', label: 'Warning', category: ReactionCategory.SYMBOLS },
    collision: { emoji: '💥', label: 'Collision', category: ReactionCategory.SYMBOLS },
    dizzy: { emoji: '💫', label: 'Dizzy', category: ReactionCategory.SYMBOLS },
    party_popper: { emoji: '🎉', label: 'Party popper', category: ReactionCategory.SYMBOLS },
    confetti: { emoji: '🎊', label: 'Confetti ball', category: ReactionCategory.SYMBOLS },
    zzz: { emoji: '💤', label: 'Zzz', category: ReactionCategory.SYMBOLS },
    sweat_drops: { emoji: '💦', label: 'Sweat drops', category: ReactionCategory.SYMBOLS },
    prohibited: { emoji: '🚫', label: 'Prohibited', category: ReactionCategory.SYMBOLS },
    ok_button: { emoji: '🆗', label: 'OK button', category: ReactionCategory.SYMBOLS },
    cool_button: { emoji: '🆒', label: 'Cool button', category: ReactionCategory.SYMBOLS },

    flag_ua: { emoji: '🇺🇦', label: 'Ukraine flag', category: ReactionCategory.FLAGS },
    flag_ca: { emoji: '🇨🇦', label: 'Canada flag', category: ReactionCategory.FLAGS },
    flag_us: { emoji: '🇺🇸', label: 'United States flag', category: ReactionCategory.FLAGS },
    flag_gb: { emoji: '🇬🇧', label: 'United Kingdom flag', category: ReactionCategory.FLAGS },
    flag_es: { emoji: '🇪🇸', label: 'Spain flag', category: ReactionCategory.FLAGS },
    flag_it: { emoji: '🇮🇹', label: 'Italy flag', category: ReactionCategory.FLAGS },
    flag_de: { emoji: '🇩🇪', label: 'Germany flag', category: ReactionCategory.FLAGS },
    flag_fr: { emoji: '🇫🇷', label: 'France flag', category: ReactionCategory.FLAGS },
    flag_pt: { emoji: '🇵🇹', label: 'Portugal flag', category: ReactionCategory.FLAGS },
    flag_nl: { emoji: '🇳🇱', label: 'Netherlands flag', category: ReactionCategory.FLAGS },
    flag_be: { emoji: '🇧🇪', label: 'Belgium flag', category: ReactionCategory.FLAGS },
    flag_ch: { emoji: '🇨🇭', label: 'Switzerland flag', category: ReactionCategory.FLAGS },
    flag_at: { emoji: '🇦🇹', label: 'Austria flag', category: ReactionCategory.FLAGS },
    flag_ie: { emoji: '🇮🇪', label: 'Ireland flag', category: ReactionCategory.FLAGS },
    flag_se: { emoji: '🇸🇪', label: 'Sweden flag', category: ReactionCategory.FLAGS },
    flag_no: { emoji: '🇳🇴', label: 'Norway flag', category: ReactionCategory.FLAGS },
    flag_dk: { emoji: '🇩🇰', label: 'Denmark flag', category: ReactionCategory.FLAGS },
    flag_fi: { emoji: '🇫🇮', label: 'Finland flag', category: ReactionCategory.FLAGS },
    flag_is: { emoji: '🇮🇸', label: 'Iceland flag', category: ReactionCategory.FLAGS },
    flag_pl: { emoji: '🇵🇱', label: 'Poland flag', category: ReactionCategory.FLAGS },
    flag_cz: { emoji: '🇨🇿', label: 'Czechia flag', category: ReactionCategory.FLAGS },
    flag_sk: { emoji: '🇸🇰', label: 'Slovakia flag', category: ReactionCategory.FLAGS },
    flag_hu: { emoji: '🇭🇺', label: 'Hungary flag', category: ReactionCategory.FLAGS },
    flag_ro: { emoji: '🇷🇴', label: 'Romania flag', category: ReactionCategory.FLAGS },
    flag_bg: { emoji: '🇧🇬', label: 'Bulgaria flag', category: ReactionCategory.FLAGS },
    flag_gr: { emoji: '🇬🇷', label: 'Greece flag', category: ReactionCategory.FLAGS },
    flag_tr: { emoji: '🇹🇷', label: 'Turkey flag', category: ReactionCategory.FLAGS },
    flag_hr: { emoji: '🇭🇷', label: 'Croatia flag', category: ReactionCategory.FLAGS },
    flag_rs: { emoji: '🇷🇸', label: 'Serbia flag', category: ReactionCategory.FLAGS },
    flag_si: { emoji: '🇸🇮', label: 'Slovenia flag', category: ReactionCategory.FLAGS },
    flag_ee: { emoji: '🇪🇪', label: 'Estonia flag', category: ReactionCategory.FLAGS },
    flag_lv: { emoji: '🇱🇻', label: 'Latvia flag', category: ReactionCategory.FLAGS },
    flag_lt: { emoji: '🇱🇹', label: 'Lithuania flag', category: ReactionCategory.FLAGS },
    flag_ru: { emoji: '🇷🇺', label: 'Russia flag', category: ReactionCategory.FLAGS },
    flag_by: { emoji: '🇧🇾', label: 'Belarus flag', category: ReactionCategory.FLAGS },
    flag_md: { emoji: '🇲🇩', label: 'Moldova flag', category: ReactionCategory.FLAGS },
    flag_ge: { emoji: '🇬🇪', label: 'Georgia flag', category: ReactionCategory.FLAGS },
    flag_am: { emoji: '🇦🇲', label: 'Armenia flag', category: ReactionCategory.FLAGS },
    flag_az: { emoji: '🇦🇿', label: 'Azerbaijan flag', category: ReactionCategory.FLAGS },
    flag_mx: { emoji: '🇲🇽', label: 'Mexico flag', category: ReactionCategory.FLAGS },
    flag_br: { emoji: '🇧🇷', label: 'Brazil flag', category: ReactionCategory.FLAGS },
    flag_ar: { emoji: '🇦🇷', label: 'Argentina flag', category: ReactionCategory.FLAGS },
    flag_cl: { emoji: '🇨🇱', label: 'Chile flag', category: ReactionCategory.FLAGS },
    flag_co: { emoji: '🇨🇴', label: 'Colombia flag', category: ReactionCategory.FLAGS },
    flag_pe: { emoji: '🇵🇪', label: 'Peru flag', category: ReactionCategory.FLAGS },
    flag_ve: { emoji: '🇻🇪', label: 'Venezuela flag', category: ReactionCategory.FLAGS },
    flag_uy: { emoji: '🇺🇾', label: 'Uruguay flag', category: ReactionCategory.FLAGS },
    flag_cu: { emoji: '🇨🇺', label: 'Cuba flag', category: ReactionCategory.FLAGS },
    flag_jp: { emoji: '🇯🇵', label: 'Japan flag', category: ReactionCategory.FLAGS },
    flag_cn: { emoji: '🇨🇳', label: 'China flag', category: ReactionCategory.FLAGS },
    flag_kr: { emoji: '🇰🇷', label: 'South Korea flag', category: ReactionCategory.FLAGS },
    flag_in: { emoji: '🇮🇳', label: 'India flag', category: ReactionCategory.FLAGS },
    flag_pk: { emoji: '🇵🇰', label: 'Pakistan flag', category: ReactionCategory.FLAGS },
    flag_bd: { emoji: '🇧🇩', label: 'Bangladesh flag', category: ReactionCategory.FLAGS },
    flag_id: { emoji: '🇮🇩', label: 'Indonesia flag', category: ReactionCategory.FLAGS },
    flag_th: { emoji: '🇹🇭', label: 'Thailand flag', category: ReactionCategory.FLAGS },
    flag_vn: { emoji: '🇻🇳', label: 'Vietnam flag', category: ReactionCategory.FLAGS },
    flag_ph: { emoji: '🇵🇭', label: 'Philippines flag', category: ReactionCategory.FLAGS },
    flag_my: { emoji: '🇲🇾', label: 'Malaysia flag', category: ReactionCategory.FLAGS },
    flag_sg: { emoji: '🇸🇬', label: 'Singapore flag', category: ReactionCategory.FLAGS },
    flag_hk: { emoji: '🇭🇰', label: 'Hong Kong flag', category: ReactionCategory.FLAGS },
    flag_tw: { emoji: '🇹🇼', label: 'Taiwan flag', category: ReactionCategory.FLAGS },
    flag_sa: { emoji: '🇸🇦', label: 'Saudi Arabia flag', category: ReactionCategory.FLAGS },
    flag_ae: { emoji: '🇦🇪', label: 'United Arab Emirates flag', category: ReactionCategory.FLAGS },
    flag_il: { emoji: '🇮🇱', label: 'Israel flag', category: ReactionCategory.FLAGS },
    flag_ir: { emoji: '🇮🇷', label: 'Iran flag', category: ReactionCategory.FLAGS },
    flag_iq: { emoji: '🇮🇶', label: 'Iraq flag', category: ReactionCategory.FLAGS },
    flag_eg: { emoji: '🇪🇬', label: 'Egypt flag', category: ReactionCategory.FLAGS },
    flag_za: { emoji: '🇿🇦', label: 'South Africa flag', category: ReactionCategory.FLAGS },
    flag_ng: { emoji: '🇳🇬', label: 'Nigeria flag', category: ReactionCategory.FLAGS },
    flag_ke: { emoji: '🇰🇪', label: 'Kenya flag', category: ReactionCategory.FLAGS },
    flag_ma: { emoji: '🇲🇦', label: 'Morocco flag', category: ReactionCategory.FLAGS },
    flag_dz: { emoji: '🇩🇿', label: 'Algeria flag', category: ReactionCategory.FLAGS },
    flag_et: { emoji: '🇪🇹', label: 'Ethiopia flag', category: ReactionCategory.FLAGS },
    flag_gh: { emoji: '🇬🇭', label: 'Ghana flag', category: ReactionCategory.FLAGS },
    flag_au: { emoji: '🇦🇺', label: 'Australia flag', category: ReactionCategory.FLAGS },
    flag_nz: { emoji: '🇳🇿', label: 'New Zealand flag', category: ReactionCategory.FLAGS },
    flag_eu: { emoji: '🇪🇺', label: 'European Union flag', category: ReactionCategory.FLAGS },
    checkered_flag: { emoji: '🏁', label: 'Checkered flag', category: ReactionCategory.FLAGS },
    pirate_flag: { emoji: '🏴‍☠️', label: 'Pirate flag', category: ReactionCategory.FLAGS },
    white_flag: { emoji: '🏳️', label: 'White flag', category: ReactionCategory.FLAGS },
    rainbow_flag: { emoji: '🏳️‍🌈', label: 'Rainbow flag', category: ReactionCategory.FLAGS },
};

export const ALL_REACTION_CODES = Object.keys(REACTION_DETAILS);
